sudo: required
services:
  - docker
before_install:
  - docker build -t remery/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true remery/docker-react npm run test 
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-768716614782"
  bucket_path: "front_end"
  on:
    branch: "main"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"